

#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

//SPI1
#define MSPI1_CLOCK_MODE     MSPI_MODE3

#define MSPI1_PRESCALLER     MSPI_FPCLK_DIVIDED_BY_128

#define MSPI1_DATA_ORDER     MSPI_MSB_FIRST

#define MSPI1_SS_MANAGE      HW_SLAVE_MANAGEMENT

#define MSPI1_DATA_SIZE      MSPI_8BIT_DATA



//SPI2
#define MSPI2_CLOCK_MODE     MSPI_MODE3


#define MSPI2_PRESCALLER     MSPI_FPCLK_DIVIDED_BY_32

#define MSPI2_DATA_ORDER     MSPI_MSB_FIRST

#define MSPI2_SS_MANAGE      HW_SLAVE_MANAGEMENT

#define MSPI2_DATA_SIZE      MSPI_8BIT_DATA



#endif /* SPI_CONFIG_H_ */
